# Generated by Django 4.2.3 on 2023-07-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('how_to_use', models.TextField()),
                ('description', models.TextField()),
                ('file_content', models.FileField(upload_to='')),
                ('status', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.category')),
            ],
        ),
    ]
