# Generated by Django 4.2.3 on 2023-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_coursedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daysaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='file_content',
            field=models.FileField(upload_to='course'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='type',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Document', 'Document')], max_length=250),
        ),
    ]
