# Generated by Django 4.2.3 on 2023-07-12 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0003_daysaccess_alter_coursedetails_file_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('payment_ref', models.CharField(max_length=250)),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.coursedetails')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
