# Generated by Django 4.2.3 on 2023-07-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_userprofile_alter_payment_student_id_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.userprofile'),
        ),
    ]
